name: Build Push Sign
on: { push: { branches: ['main'] } }

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v1

      - name: Login to GitHub
        uses: docker/login-action@v1.9.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build+push
        env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          push: true
          tags: ghcr.io/${GITHUB_REPOSITORY_OWNER}/cosign-keyless-action

      - uses: sigstore/cosign-installer@main

      - name: Sign the images
        env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          COSIGN_EXPERIMENTAL: 1
        run: |
          cosign sign \
            ghcr.io/${GITHUB_REPOSITORY_OWNER}/cosign-keyless-action

      - name: Verify the pushed tags
        env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          COSIGN_EXPERIMENTAL: 1
        run: cosign verify ghcr.io/${GITHUB_REPOSITORY_OWNER}/cosign-action-action
        
